### ISSUE TITLE
improve immutable data

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/rxjs-react-example#7]
Take a look on immutable.js, refactor stores using it, and also take a look on shouldComponentUpdate from https://github.com/omniscientjs/omniscient

**Comment by mauriciosoares** [comment]
http://reapp.io/2015/03/11/Simplify-Flux-with-Immutable-js-and-Fynx/

**Comment by mauriciosoares** [comment]
working! :D

**Comment by rafaelrinaldi** [comment]
Feels good.
